services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-keyfile:/tmp/mongo-keyfile:ro
      - ./mongo-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh:ro
    entrypoint: ["/bin/bash", "/usr/local/bin/custom-entrypoint.sh"]
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/mongo-keyfile"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  mongo-init:
    image: mongo:7.0
    depends_on:
      mongo:
        condition: service_healthy
    command: >
      mongosh --host mongo:27017 -u root -p example --authenticationDatabase admin --eval "
      try {
        rs.status();
        print('Replica set already initialized');
      } catch (err) {
        if (err.codeName === 'NotYetInitialized') {
          rs.initiate({
            _id: 'rs0',
            members: [{ _id: 0, host: 'mongo:27017' }]
          });
          print('Replica set initialized successfully');
        }
      }
      "
    restart: "no"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: mongodb://root:example@mongo:27017/kanban-board?authSource=admin&replicaSet=rs0
      MONGODB_URI: mongodb://root:example@mongo:27017/kanban-board?authSource=admin&replicaSet=rs0
      JWT_SECRET: mysecretkey
      PORT: 3000
      N8N_WEBHOOK_URL: http://n8n:5678/webhook/kanban-export
      EXPORT_NOTIFICATION_EMAIL: team@example.com
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully
    command: sh -c "sleep 3 && pnpm prisma db push && pnpm run start:prod"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000

  n8n:
    image: n8nio/n8n:1.106.3
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Lima
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_OWNER_EMAIL=admin@localhost.local
      - N8N_OWNER_PASSWORD=Admin123456
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongo_data:
  n8n_data: